name: ensemble-solar-wind-connectivity
channels:
  - conda-forge
dependencies:
  # Base python
  - python>=3.8.5
  # Conda dependencies
  - astropy==5.0
  - cartopy==0.18.0
  - geos==3.8.0
  - h5py==3.6.0
  - matplotlib==3.5.0
  - numpy==1.21.5
  - pandas==1.4.2
  - pdoc3==0.9.2
  - pillow==8.4.0
  - proj==7.0.1
  - pyshp==2.1.3
#  - python-dateutil==2.8.2
#  - pytz==2021.3
#  - qt==5.9.7
  - scipy==1.7.3
  - scikit-learn==1.0.2
  - shapely==1.7.1
#  - termcolor==1.1.0
#  - xmltodict==0.12.0
  # Pip Dependencies
  - setuptools>=52.0.0
  - pip
#  - pip:
#      - ai.cdas
 #     - pyside2==5.15.2.1
